### ISSUE TITLE
无法识别

### ISSUE THREAD

**Issue by otaku1951** [yumemor/ysale-sms#1]
貌似验证码图片无法识别

**Comment by akarineren** [comment]
安装了 node-tesseract 和 gm 依赖吗(不是 npm install)?

**Comment by yumemor** [comment]
目前只能识别出 比较清晰的验证码 识别率和验证码清晰度有关 比如 这种 识别率在百分百
![image](https://cloud.githubusercontent.com/assets/11767814/16368548/edaa7f44-3c61-11e6-9b1a-0508bcaf1e55.png)

**Comment by otaku1951** [comment]
刚才启动不了是因为我的node版本太低，现在这个我怀疑gm上是不是还有依赖其他组件？如imagemagick 和 graphicsmagick

我在http://app.ysale.cn/jyz5/PHP/verifycode.php 这个地址看验证码好像其实挺清晰的

**Comment by akarineren** [comment]
看了 REAMDE 了吗？需要安装依赖 

``` shell
brew install tesseract --with-all-languages
brew install imagemagick
brew install graphicsmagick
```
