### ISSUE TITLE
没有找到‘superagent’模块？？？

### ISSUE THREAD

**Issue by fonghub** [yumemor/ysale-sms#2]
出现图片里面这个错误，什么情况？？？
![_20160628122308](https://cloud.githubusercontent.com/assets/9565963/16403779/3ccd5b86-3d2b-11e6-9fc0-5c450c574bce.png)

**Comment by akarineren** [comment]
你没有 npm install 

你应该也没有安装 tesseract 和 gm 依赖。 windows 安装比较麻烦

**Comment by fonghub** [comment]
我安装了tesseract ，gm，superagent，cheerio，然后就开始显示这个了。
tesseract 和 gm 依赖怎么安装？
![filehelper_1467090377465_11](https://cloud.githubusercontent.com/assets/9565963/16404405/4b6c98d6-3d31-11e6-953d-281323e4979d.png)

**Comment by akarineren** [comment]
我没有使用 windows  具体你可以查查教程如何安装  应该比较麻烦 建议你使用 linux 系统 

还有 你上面安装的那四个组件是 node 需要的 ，其中 te 和 gm 需要你本地的库进行调用 你需要安装的是这俩个本地库 不只是 npm install 就好了

**Comment by akarineren** [comment]
我等会测试下在 win 上面安装
